server:
  port: 8080
spring:
  datasource:
    username: Books
    password: wYkkBN2iEY42CCYJ
    url: jdbc:mysql://139.198.164.14:3306/books?userUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver